# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.3
yarn_build=2
loader_version=0.16.7
fabric_version=0.107.0+1.21.3
fabric_kotlin_version=1.12.3+kotlin.2.0.21
kache_version=1.0.5
inject_version=1.3.1

# Mod Properties
mod_version=3.1
maven_group=dev.andante
