# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# minecraft
minecraft_version=25w32a

# fabric
yarn_build=7
loader_version=0.17.2
fabric_version=0.131.2+1.21.9

# kotlin
kotlin_version=2.2.0
fabric_kotlin_version=1.13.4

# mod properties
mod_version=3.4.1
maven_group=net.mcbrawls
mod_id=audience

# dependencies

kache_version=1.0.5
inject_version=3.1.4
